### ISSUE TITLE
post_recipient_view explication

### ISSUE THREAD

**Issue by k0pernicus** [peopledoc/django-docusign#89]
I try to understand how to customize this Django module, based on my case:  
1. The creator of the document will create, using `XXX/views/sender`, the tabs;
2. The signer will fill the blanks and sign only the document, pre-processed by the creator.

So, in this example, I have two distinct users:  
* the creator of the document, who can edit the tabs,
* the signer, who can fill the blanks and sign the documents.

In the model, we have only one user model: `Signer`.  
Is `Signer` is supposed to be the creator and the signer of the document?

Also, do you have any idea how to to restrict the possibilities (to edit/modify tabs and signature) for both the creator and the signer?  
I checked the code of the module, and I found that the `post_recipient_view` method calls only `XXX/views/recipient`, and not `XXX/views/sender`.  
So can we consider the `Signer` model as a recipient only?

Thanks in advance, and thanks for this awesome work :)

**Comment by zebuline** [comment]
@k0pernicus indeed, a `Signer` is a `recipient`, and only a `recipient`. There is no possibility for now to configure a `sender`, but you can propose some changes if you want.
We (PeopleDoc) are using this lib for our products, and for the moment this implementation is enough for our needs; of course if you want to enhance some parts of the lib, your propositions/PRs are welcome !
